title: Lucy Ware
description: The difference between the typography used in different form of TV
footer_text: Copyright 2021 Lucy Ware
header_feature_image: ../uploads/tv-typograhy-banner.png
header_text: TV TYPOGRAPHY
header_text_color: "#090a0a"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
