title: Lucy Ware
description: The difference between the typography used in different form of TV
footer_text: Copyright 2021 Lucy Ware
header_feature_image: ../uploads/original.jpg
header_text: TV TYPOGRAPHY
header_text_color: "#effbfb"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
